<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-BMS.Worker-4299D031-0A9B-451C-B16C-71C31D7F0879</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BMS.Application\BMS.Application.csproj" />
    <ProjectReference Include="..\BMS.Infrastructure\BMS.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Filtering\" />
    <Folder Include="Models\" />
  </ItemGroup>
</Project>
